### PR TITLE
Source generated file support

### LINKED ISSUE #11: Error when trying to get definition without results
For example when navigating into `Func<T, TResult>` trying to get definition of delegate causes an error. Should check if any locations were returned first.

### LINKED ISSUE #18: Handler for `textDocument/reference` when source generators are involved?
I use Godot engine with C#, which involves the use of source-generators.  I noticed that `textDocument/reference` fails when I try it on any identifier that is referenced in something that's generated, and I'm wondering if it can be solved in a similar way that this plugin is currently solving `textDocument/definition`?

One of the generators I use is [GodotOnReady](https://github.com/31/GodotOnReady), such that if I try `vim.lsp.buf.references()` on a member like this:
```cs
[OnReadyGet("something")] private Node _something;
```
I get the following error:
```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1735: index out of range
stack traceback:
        [C]: in function '_str_byteindex_enc'
        /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1735: in function 'locations_to_items'
        /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:193: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1383: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Alas, I don't even know exactly how source generation works (I will be reading up) -- how much more complicated is this problem compared to the problem that this plugin already solves?

### LINKED ISSUE #28: Go to definition fails after doing :LspRestart
I have found that I can go to a third party dll class/method definition just fine, but if I run `:LspRestart` and then attempt to do that same thing again, I get this error:

image

BUT - this issue goes away completely if I uncomment [this line](https://github.com/Hoffs/omnisharp-extended-lsp.nvim/blob/main/lua/omnisharp_extended.lua#L166) and then comment out the line after that.  I assume there's a reason we don't want to uncomment this though

### PR DESCRIPTION
**Pull request by Hoffs**
resolves #18 
resolves #11 
resolves #28

### CODE REVIEW

**Comment by Hoffs** [comment]
need to test on windows before merging

**Comment by Hoffs** [comment]
windows paths hard ( https://github.com/neovim/neovim/issues/23006 ), try to rely on `vim.uri_to_bufnr`

File: lua/omnisharp_utils.lua [hunk 1]
```diff
@@ -0,0 +1,175 @@
...
+-- params = {
+--   AssemblyName
+--   TypeName
+--   ProjectName
+--   VersionNumber
+--   Language
+-- }
+OU.load_metadata_doc = function(params, lsp_client)
+  local result, err = lsp_client.request_sync("o#/metadata", params, 10000)
+  if not err then
```
Comment (Hoffs) [inline lua/omnisharp_utils.lua:47]: metadata can return empty response if document is not found

**Comment by Hoffs** [comment]
Probably ready to merge, need to reincorporate #30
